# Generated by Django 5.0.6 on 2024-08-04 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='user',
        ),
    ]
