# Generated by Django 5.0.6 on 2024-07-26 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('specialized_skills', models.CharField(max_length=500)),
                ('resume', models.FileField(upload_to='pdfs/')),
                ('applying_for', models.CharField(choices=[('Backend', 'backend'), ('Frontend', 'frontend'), ('Database', 'database'), ('APIs', 'apis'), ('SEO', 'seo')], max_length=500)),
                ('date_applied', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
