# Generated by Django 5.0.6 on 2024-08-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_alter_address_item_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='placed_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
