# Generated by Django 5.0.6 on 2024-08-10 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0006_cancel'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='status',
            field=models.CharField(blank=True, choices=[('shipped', 'shipped'), ('on the way', 'on the way')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cancel',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom.item'),
        ),
    ]
