# Generated by Django 5.0.6 on 2024-08-10 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0007_address_status_alter_cancel_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='custom_status',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='expected_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='status',
            field=models.CharField(blank=True, choices=[('shipped', 'shipped'), ('on the way', 'on the way'), ('out for delivery', 'out for delivery'), ('near to you', 'near to you'), ('order confirmed', 'order confirmed'), ('delivered', 'delivered'), ('could not deliver!', 'could not deliver'), ('waiting for seller to proceed', 'waiting for seller to proceed'), ('will be deliver shortly', 'will be deliver shortly')], max_length=100, null=True),
        ),
    ]
