# Generated by Django 5.0.6 on 2024-08-10 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0008_address_custom_status_address_expected_delivery_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='custom_status',
            field=models.CharField(blank=True, default='Delivery date will be available soon.', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='status',
            field=models.CharField(blank=True, choices=[('shipped', 'shipped'), ('on the way', 'on the way'), ('out for delivery', 'out for delivery'), ('near to you', 'near to you'), ('order confirmed', 'order confirmed'), ('delivered', 'delivered'), ('could not deliver!', 'could not deliver'), ('waiting for seller to proceed', 'waiting for seller to proceed'), ('will be deliver shortly', 'will be deliver shortly')], default='Order confirmed', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Fast delivery', 'Fast delivery'), ('deliver on my given time', 'deliver on my given time'), ('read my message', 'read my message')], max_length=500)),
                ('message', models.CharField(max_length=50000)),
                ('attach_image', models.ImageField(upload_to='help_request_images/')),
                ('raised_on', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
