# Generated by Django 5.0.6 on 2024-08-10 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0009_alter_address_custom_status_alter_address_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='help',
            name='contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='help',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='help',
            name='raised_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
