# Generated by Django 5.0.6 on 2024-08-11 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0010_help_contact_help_email_alter_help_raised_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='slug',
        ),
    ]
