# Generated by Django 5.0.6 on 2024-08-11 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0011_remove_item_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
