# Generated by Django 5.0.6 on 2024-08-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0016_sellproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellproducts',
            name='message',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='sellproducts',
            name='status',
            field=models.CharField(blank=True, choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Pending', 'Pending'), ('Coming to pick', 'Coming to pick')], default='Pending', max_length=200, null=True),
        ),
    ]
