# Generated by Django 5.0.6 on 2024-08-12 05:24

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0017_sellproducts_message_sellproducts_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', tinymce.models.HTMLField()),
                ('attachment_pdf', models.FileField(upload_to='attachments/')),
            ],
        ),
    ]
