# Generated by Django 5.0.6 on 2024-08-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0018_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='date_posted',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
