# Generated by Django 5.0.6 on 2024-07-24 03:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('collage document', 'collage document'), ('government document', 'government document'), ('other document', 'other document')], max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('document', models.ImageField(upload_to='images/')),
                ('person_name', models.CharField(max_length=100)),
                ('document_id', models.CharField(max_length=100)),
                ('country', models.CharField(choices=[('india', 'india'), ('america', 'america'), ('china', 'china'), ('bangladesh', 'bangladesh'), ('madhya pradesh', 'madhya pradesh'), ('assam', 'assam'), ('others', 'others')], max_length=100)),
                ('is_legal', models.CharField(choices=[('legal', 'legal'), ('illegal', 'illegal'), ('both', 'both')], max_length=100)),
                ('nominee', models.CharField(max_length=100)),
                ('nominee_contact', models.CharField(max_length=100)),
                ('type_doc', models.CharField(choices=[('file', 'file'), ('list', 'list')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
