# Generated by Django 5.0.6 on 2024-07-28 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=1000)),
                ('category', models.CharField(choices=[('Personal', 'Personal'), ('Work', 'Work'), ('Others', 'Others')], max_length=1000)),
                ('important', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=5000)),
                ('date_to_accomplish', models.DateField()),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
