# Generated by Django 5.0.6 on 2024-08-04 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_remove_job_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Get_Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('type', models.CharField(choices=[('Student', 'Student'), ('Working proffecional', 'Working Proffecional'), ('Graduate', 'Graduate'), ('Learner', 'Learner')], max_length=100)),
                ('background', models.CharField(choices=[('IT', 'IT'), ('Non IT', 'Non IT'), ('Finance', 'Finance'), ('Medical', 'Medical'), ('Not in the list', 'Not in the list')], max_length=100)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('date_applied', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
