# Generated by Django 5.0.6 on 2024-08-05 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_homework_userhomework'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userhomework',
            name='homework',
        ),
        migrations.RemoveField(
            model_name='userhomework',
            name='user',
        ),
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('attachments', models.FileField(upload_to='assignments/')),
                ('due_on', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
                ('listed', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='HomeWork',
        ),
        migrations.DeleteModel(
            name='UserHomework',
        ),
    ]
