# Generated by Django 5.0.6 on 2024-08-07 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_posts_delete_addpost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalAssets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=100)),
                ('asset', models.FileField(blank=True, null=True, upload_to='assets/')),
                ('type', models.CharField(choices=[('PDf', 'PDF'), ('Folder', 'Folder'), ('File', 'File'), ('Image', 'Image'), ('Audio', 'Audio'), ('Video', 'Video'), ('Zip', 'Zip'), ('Other', 'Other')], max_length=100)),
                ('text', models.CharField(max_length=1000)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
