# Generated by Django 5.0.6 on 2024-08-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_digitalassets'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalassets',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
