from django.urls import path, include
from .views import *

urlpatterns = [
    path("create_notes/", create_notes, name='create_notes'),
    path("view_notes/", view_notes, name='view_notes'),
    path("note/<int:pk>/", note_detail, name='note_detail'),
    path("delete_notes/<int:note_id>/", delete_notes, name='delete_notes'),
    path("note/<int:pk>/edit", edit_note, name='edit_note'),
    path("wikipedia/", search_wikipedia, name='wikipedia'),
    path("translator/", translator, name='translator'),
    path("grammar_check/", grammar_check, name='grammar_check'),
    path("store_ebooks/", store_ebooks, name='store_ebooks'),
    path("ebook_detail/<int:pk>/", ebook_detail, name='ebook_detail'),
    path("delete_ebooks/<int:ebook_id>/", delete_ebooks, name='delete_ebooks'),
    path("career_recommendation/", career_recommendation_view, name='career_recommendation'),
    path("job_posting/", job_posting, name='job_posting'),
    path("job_detail/<int:pk>/", job_detail, name='job_detail'),
    path("apply_job/<int:job_id>/", apply_job, name='apply_job'),
    path("applied_jobs/", applied_jobs, name='applied_jobs'),
    path("add_assignments/", add_assignments, name='add_assignments'),
    path("mark/<int:pk>/", mark, name='mark'),
    path("delete_assignment/<int:pk>/", delete_assignment, name='delete_assignment'),
    path("edit_assignments/<int:pk>/", edit_assignments, name='edit_assignments'),
    path("do_work/<int:pk>/", do_work, name='do_work'),
    path("attachments/<int:pk>/", attachments, name='attachments'),
    path("set_profile/", set_profile, name='set_profile'),
    path("browse_profile/", browse_profile, name='browse_profile'),
    path("post/", post, name='post'),
    path("manage_posts/", manage_posts, name='manage_posts'),
    path("delete_posts/<int:pk>/", delete_posts, name='delete_posts'),
    path('download_all_images/', download_all_images, name='download_all_images'),
    path("all_students/", all_students, name='all_students'),
    path("user_profile/<int:pk>/", user_profile,name='user_profile'),
    path('profile/edit/', edit_profile, name='edit_profile'),
    path("assets/",assets,name='assets'),
    path("delete_assets/<int:pk>/",delete_assets,name='delete_assets'),
    path("edit_assets/<int:pk>/",edit_assets,name='edit_assets'),
]

